### PR TITLE
Fractalis Major Update

### PR DESCRIPTION
**Pull request by sherzinger**
This is a major update of Fractalis back-end, front-end, and transmart-fractalis

**IMPORTANT:** Please create a new transmartApp image with the newest transmart-fractalis code before merging this PR. Otherwise things will break.

### CODE REVIEW

**Review by burtbeckwith — APPROVED** [review]

**Comment by burtbeckwith** [comment]
The latest war in artifactory (transmart-18.1-20180806.141930-2.war) includes the most recent transmart-fractalis changes, so this is ready to merge

**Comment by sherzinger** [comment]
Please do not merge this yet.
I'll wait for the email thread to be resolved, so I can properly test this with docker.

**Comment by burtbeckwith** [comment]
transmart-18.1-20180807.141544-1.war is available with the GSP fix

**Comment by recursethis** [comment]
Sascha, if you would like to test this build locally, you can build it locally and update the `.env` file with the new version, for example
```bash
$ cd docker-images/i2b2transmart
$ docker build -t dbmi/i2b2transmart:release-18.1-beta-new-version ./
$ cd ../deployments/i2b2transmart/quickstart
# update .env and quickstart.env values
# follow deploy instructions
$ docker-compose up -d db
# wait for database to load
$ docker-compose up -d
```

**Pull request merged**
